const artifacts = {
  gyodong: { no:'01', name:'교동금관', hanja:'校洞金冠', site:'경상북도 경주시 교동 일대 고분', focus:'관테를 따라 이어지는 장식과 균형 잡힌 실루엣', line:'나뭇가지와 사슴뿔을 닮은 세움장식, 곱은옥과 달개가 어우러진 금관입니다.', detail:'둥근 관테 위에 여러 세움장식을 세우고 관테 아래에 장식을 매단 신라 금관입니다. 얇은 금판을 오려 만든 나뭇가지형 장식과 사슴뿔형 장식이 전체 실루엣을 결정합니다. 관테와 세움장식에 뚫은 구멍은 곱은옥과 금제 달개를 연결한 흔적을 보여 줍니다.', points:['관테 위로 솟은 나뭇가지형·사슴뿔형 세움장식','관테와 장식의 작은 구멍, 그리고 연결 방식','푸른빛 곱은옥과 금제 달개의 대비'], shape:'balanced' },
  geumgwanchong: { no:'02', name:'금관총 금관', hanja:'金冠塚 金冠', site:'경상북도 경주시 금관총', focus:'높고 화려한 세움장식과 풍부한 매달림 장식', line:'신라 금관의 존재를 널리 알린 대표적인 금관으로, 높이감 있는 세움장식이 특징입니다.', detail:'원형의 관테 위에 나뭇가지형 장식과 사슴뿔형 장식을 세운 형태입니다. 관테와 세움장식의 작은 장식은 빛과 움직임에 따라 반짝였을 것으로 보입니다. 초기 조사 기록에는 한계가 있어, 이 전시는 피장자나 출토 위치를 단정하지 않고 금관의 조형성과 제작 흔적을 중심으로 살펴봅니다.', points:['위쪽으로 길게 뻗어 높이를 만드는 세움장식','사슴뿔을 닮은 갈라진 장식의 윤곽','금판의 절단선·점무늬·작은 구멍'], shape:'tall', photo:{url:'https://commons.wikimedia.org/wiki/Special:FilePath/%EA%B8%88%EA%B4%80%EC%B4%9D%EA%B8%88%EA%B4%80.jpg?width=960', source:'https://commons.wikimedia.org/wiki/File:%EA%B8%88%EA%B4%80%EC%B4%9D%EA%B8%88%EA%B4%80.jpg', credit:'국가유산청 · 공공누리 제1유형'} },
  seobongchong: { no:'03', name:'서봉총 금관', hanja:'瑞鳳塚 金冠', site:'경상북도 경주시 서봉총', focus:'섬세한 금세공과 리듬감 있는 매달림 장식', line:'정교한 세움장식과 관테에 달린 장신구가 신라 금세공의 섬세함을 보여 줍니다.', detail:'관테와 세움장식, 매달림 장식으로 이루어진 신라 금관의 기본 구성을 갖추고 있습니다. 세움장식의 가지와 뿔 모양, 관테 아래로 늘어진 장식은 전체에 리듬감 있는 윤곽을 만듭니다. 이 화면에서는 발굴의 역사보다 금관의 조형과 공예 기법을 중심으로 다른 두 금관과의 비례를 비교합니다.', points:['관테 위 장식의 폭과 높이가 만드는 비례','나뭇가지와 사슴뿔을 연상시키는 갈라진 끝','얇은 금판의 점무늬와 가장자리 처리'], shape:'wide', photo:{url:'https://commons.wikimedia.org/wiki/Special:FilePath/Royal%20Crown%20of%20Silla.%20National%20Museum%20of%20Korea.jpg?width=960', source:'https://commons.wikimedia.org/wiki/File:Royal_Crown_of_Silla._National_Museum_of_Korea.jpg', credit:'Ismoon · CC BY-SA'} }
};
const order = Object.keys(artifacts); const app = document.querySelector('#content');

function crownSVG(shape='balanced', labeled=false) {
 const scale = shape==='tall'? 'translate(0 -18) scale(1.04 1.14)' : shape==='wide'? 'translate(-10 5) scale(1.12 .97)' : '';
 const branches = shape==='wide' ? 'M100 257V105l-35-35m35 70 36-32 M200 257V74l-28-32m28 68 30-32 M300 257V105l34-35m-34 70-35-32' : 'M105 257V116L72 79m33 71 32-29 M200 257V67l-27-31m27 65 30-31 M295 257V116l34-37m-34 71-33-29';
 return `<svg class="crown-svg ${labeled?'labeled':''}" viewBox="0 0 400 340" role="img" aria-label="금관 형태를 보여 주는 비교용 일러스트"><g transform="${scale}" fill="none" stroke="#f1cb69" stroke-linecap="round" stroke-linejoin="round"><path d="${branches}" stroke-width="13"/><path d="M58 264 Q200 285 342 264 L333 300 Q200 316 67 300Z" fill="#d3a636" stroke-width="3"/><path d="M78 279Q200 295 322 279" stroke="#ffe9a7" stroke-width="2"/><g fill="#52a99f" stroke="#b4e0d5" stroke-width="2"><path d="M92 292q9 16 18 0q-9-17-18 0M140 299q8 15 16 0q-8-16-16 0M244 299q8 15 16 0q-8-16-16 0M290 292q9 16 18 0q-9-17-18 0"/></g><g stroke-width="2" opacity=".95"><path d="M83 303v20m0 0 8 8m-8-8-8 8M123 306v22m0 0 8 8m-8-8-8 8M277 306v22m0 0 8 8m-8-8-8 8M317 303v20m0 0 8 8m-8-8-8 8"/></g><path d="M70 273 Q200 244 330 273" stroke="#fff0b2" stroke-width="2" stroke-dasharray="2 7"/></g>${labeled?`<g fill="#f8ecd0" font-family="sans-serif" font-size="12"><text x="17" y="90">세움장식</text><path d="M70 94L98 120" stroke="#f8ecd0"/><text x="312" y="250">관테</text><path d="M305 253L275 273" stroke="#f8ecd0"/><text x="10" y="320">곱은옥</text><path d="M58 315L95 292" stroke="#f8ecd0"/><text x="305" y="335">달개</text><path d="M300 330L318 323" stroke="#f8ecd0"/></g>`:''}</svg>`;
}
function link(path,label,cls='') { return `<a class="${cls}" href="#${path}">${label}</a>`; }
function home(){ return `<section class="hero"><div><p class="kicker">DIGITAL EXHIBITION · GYEONGJU</p><h1>신라의 <span>세 금관</span></h1><p class="hero-copy">금으로 만든 숲, 신라의 왕관을 가까이에서 만나다.<br>세 점의 금관을 비교하며 세움장식, 곱은옥, 달개의 서로 다른 리듬을 발견해 보세요.</p>${link('/collection','세 금관 비교하기 <span aria-hidden="true">→</span>','primary')}<div class="hero-meta"><div><strong>3</strong>비교할 금관</div><div><strong>4</strong>관찰 요소</div><div><strong>01—03</strong>전시 순서</div></div></div><div class="hero-art" aria-hidden="true"><i class="orbit"></i><i class="orbit two"></i>${crownSVG('balanced')}</div></section>`; }
function collection(){return `<section class="page"><div class="page-heading"><p class="kicker">COLLECTION 01 — 03</p><h1 class="page-title">세 개의 금관,<br>세 가지 빛</h1><p class="intro">비슷한 듯 다른 세 금관의 장식과 비례를 비교해 보세요. 각 카드를 선택하면 관찰 지점과 제작 흔적을 더 자세히 살펴볼 수 있습니다.</p></div><div class="collection-grid">${order.map(id=>card(artifacts[id],id)).join('')}</div></section>`}
function card(a,id){const visual=a.photo?`<figure class="card-photo"><img src="${a.photo.url}" alt="${a.name} 사진" loading="lazy"><figcaption><a href="${a.photo.source}" target="_blank" rel="noopener">${a.photo.credit}</a></figcaption></figure>`:`<div class="card-art">${crownSVG(a.shape)}</div>`;return `<article class="artifact-card"><span class="artifact-number">${a.no} / SILLA CROWN</span>${visual}<h2>${a.name} <small>${a.hanja}</small></h2><p>${a.focus}</p><div class="card-detail"><div><strong>출토지</strong>${a.site.replace('경상북도 ','')}</div><div><strong>관찰 요소</strong>세움장식 · 관테</div></div>${link('/artifact/'+id,'자세히 살펴보기 →','text-button')}</article>`}
function detail(id){const a=artifacts[id]||artifacts.gyodong;const idx=order.indexOf(id);const prev=order[(idx+2)%3],next=order[(idx+1)%3];return `<section class="page"><div class="breadcrumbs"><a href="#/collection">유물 비교</a><span>/</span><span>${a.name}</span></div><div class="detail-layout"><div><p class="kicker">${a.no} / SILLA GOLD CROWN</p><h1 class="detail-title">${a.name} <small>${a.hanja}</small></h1><p class="detail-lead">${a.line}</p><div class="facts"><div><strong>출토지</strong>${a.site}</div><div><strong>분류</strong>신라 · 금속공예 · 관모 장신구</div><div><strong>소장 정보</strong>공식 소장품 설명으로 재확인 필요</div><div><strong>표현 자료</strong>비교용 도식 일러스트</div></div><p class="body-copy">${a.detail}</p></div><div class="detail-visual"><div class="visual-label"><span>관찰 안내</span><span>도식 자료</span></div>${crownSVG(a.shape,true)}<div class="visual-tools"><button type="button" data-zoom="${a.shape}">확대해서 보기</button><button type="button" data-labels="${a.shape}">표시 숨기기</button></div></div></div><div class="detail-sections"><section class="info-block"><h2>눈여겨볼 특징</h2><ul>${a.points.map(x=>`<li>${x}</li>`).join('')}</ul></section><section class="info-block"><h2>어디를 볼까요?</h2><p><b>세움장식</b>은 관테 위로 솟은 장식입니다. <b>관테</b>는 머리를 두르는 띠 부분이며, <b>곱은옥</b>과 <b>달개</b>는 그 주변에 연결된 장식입니다.</p></section><section class="info-block wide"><h2>세 금관 비교</h2><table class="comparison-table"><thead><tr><th>유물</th><th>두드러지는 인상</th><th>비교하며 볼 점</th></tr></thead><tbody>${order.map(key=>{let x=artifacts[key];return `<tr><th>${x.name}</th><td>${x.focus}</td><td>${x.points[0]}</td></tr>`}).join('')}</tbody></table></section><section class="info-block wide"><h2>자료 출처 및 이용 안내</h2><p class="source-note">이 화면의 금관 이미지는 실물 사진이 아닌, 비교를 돕기 위한 도식 일러스트입니다. 실제 사진·3D 모델을 넣기 전에는 유물명, 출토지, 소장기관, 유물번호와 이용 조건을 각 기관의 공식 설명에서 확인해 주세요. 참고: <a href="https://gyeongju.museum.go.kr/" target="_blank" rel="noopener">국립경주박물관</a> · <a href="https://www.emuseum.go.kr/" target="_blank" rel="noopener">e뮤지엄</a> · <a href="https://www.heritage.go.kr/" target="_blank" rel="noopener">국가유산포털</a></p></section></div><nav class="pager" aria-label="이전 다음 유물"><a href="#/artifact/${prev}">← ${artifacts[prev].name}</a><a href="#/collection">목록으로</a><a href="#/artifact/${next}">${artifacts[next].name} →</a></nav></section>`}
function about(){return `<section class="page about"><p class="kicker">ABOUT THE EXHIBITION</p><h1 class="page-title">금으로 만든 숲을<br>천천히 살펴보기</h1><p>이 전시는 교동금관, 금관총 금관, 서봉총 금관을 나란히 놓고 공통된 형식과 서로 다른 조형을 살펴봅니다. 화려함보다 세부 관찰과 비교에 집중합니다.</p><h2>관람 방법</h2><ol><li>유물 비교에서 세 금관의 실루엣과 출토지를 먼저 확인합니다.</li><li>상세 화면의 도식에서 세움장식, 관테, 곱은옥, 달개의 위치를 확인합니다.</li><li>비교표를 통해 각 유물에서 두드러지는 부분을 나란히 살펴봅니다.</li></ol><h2>자료를 추가할 때</h2><p>현재 준비된 3D 파일은 금관 자료가 아니므로 전시에 사용하지 않았습니다. 실제 사진 또는 3D 자료를 넣을 때에는 해당 파일의 소장기관, 유물번호, 이용 조건과 촬영 각도를 함께 기록해 주세요.</p></section>`}
function render(){const r=location.hash.slice(1)||'/';let html=r==='/collection'?collection():r==='/about'?about():r.startsWith('/artifact/')?detail(r.split('/')[2]):home();app.innerHTML=html;app.focus();bindUI();}
function bindUI(){document.querySelectorAll('[data-zoom]').forEach(b=>b.addEventListener('click',()=>{const d=document.querySelector('#zoom-dialog');d.innerHTML=`<div class="zoom-inner">${crownSVG(b.dataset.zoom,true)}<button class="close-dialog" autofocus>닫기</button></div>`;d.querySelector('button').addEventListener('click',()=>d.close());d.showModal()}));document.querySelectorAll('[data-labels]').forEach(b=>b.addEventListener('click',()=>{let svg=b.closest('.detail-visual').querySelector('.crown-svg');let hide=svg.classList.toggle('labels-off');svg.querySelectorAll('text,path[stroke="#f8ecd0"]').forEach(x=>x.style.display=hide?'none':'');b.textContent=hide?'표시 보이기':'표시 숨기기';}));}
window.addEventListener('hashchange',render);render();
